version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  build:
    commands:
      - docker build -t frontend-image .
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: build
