version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  build:
    commands:
      - docker build -t frontend-image .

artifacts:
  files: 
    - '**/*'              # Includes all files and subdirectories from the root directory
    - 'appspec.yml'       # Includes the appspec.yml file
    - 'scripts/**'  
